package msgs
type WebcastSocialMessage struct {
	Streamer string `json:"streamer"`
	FollowCount string `json:"followCount"`
	ShareDisplayStyle string `json:"shareDisplayStyle"`
	PublicAreaMessageCommon struct {
		ScrollGapCount string `json:"scrollGapCount"`
		AnchorScrollGapCount string `json:"anchorScrollGapCount"`
		ReleaseToScrollArea bool `json:"releaseToScrollArea"`
		AnchorReleaseToScrollArea bool `json:"anchorReleaseToScrollArea"`
	} `json:"publicAreaMessageCommon"`
	Action string `json:"action"`
	ShareTarget string `json:"shareTarget"`
	ShareCount string `json:"shareCount"`
	Common struct {
		CreateTime string `json:"createTime"`
		LogId string `json:"logId"`
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		FromIdc string `json:"fromIdc"`
		ToIdc string `json:"toIdc"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
		RoomId string `json:"roomId"`
		DisplayText struct {
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
			DefaultFormat struct {
				UseHeighLightColor bool `json:"useHeighLightColor"`
				UseRemoteClor bool `json:"useRemoteClor"`
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
			} `json:"defaultFormat"`
			PiecesList []*struct {
				Type float64 `json:"type"`
				Format struct {
					FontSize float64 `json:"fontSize"`
					UseHeighLightColor bool `json:"useHeighLightColor"`
					UseRemoteClor bool `json:"useRemoteClor"`
					Color string `json:"color"`
					Bold bool `json:"bold"`
					Italic bool `json:"italic"`
					Weight float64 `json:"weight"`
					ItalicAngle float64 `json:"italicAngle"`
				} `json:"format"`
				StringValue string `json:"stringValue"`
				UserValue struct {
					User struct {
						AvatarThumb struct {
							OpenWebUrl string `json:"openWebUrl"`
							IsAnimated bool `json:"isAnimated"`
							UrlListList []string `json:"urlListList"`
							Uri string `json:"uri"`
							Height string `json:"height"`
							Width string `json:"width"`
							AvgColor string `json:"avgColor"`
							ImageType float64 `json:"imageType"`
						} `json:"avatarThumb"`
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						Deprecated21 string `json:"deprecated21"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						PushFollow bool `json:"pushFollow"`
						FollowInfo struct {
							FollowingCount string `json:"followingCount"`
							FollowerCount string `json:"followerCount"`
							FollowStatus string `json:"followStatus"`
							PushStatus string `json:"pushStatus"`
						} `json:"followInfo"`
						WithCommercePermission bool `json:"withCommercePermission"`
						UserRole float64 `json:"userRole"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						EnableIchatImg string `json:"enableIchatImg"`
						Status float64 `json:"status"`
						Deprecated29 string `json:"deprecated29"`
						TopVipNo string `json:"topVipNo"`
						BgImgUrl string `json:"bgImgUrl"`
						Constellation string `json:"constellation"`
						VerifiedReason string `json:"verifiedReason"`
						Id string `json:"id"`
						Deprecated1 string `json:"deprecated1"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						Deprecated18 string `json:"deprecated18"`
						Deprecated16 bool `json:"deprecated16"`
						BioDescription string `json:"bioDescription"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						IsFollower bool `json:"isFollower"`
						Nickname string `json:"nickname"`
						Deprecated3 float64 `json:"deprecated3"`
						CreateTime string `json:"createTime"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						Deprecated4 string `json:"deprecated4"`
						Deprecated8 float64 `json:"deprecated8"`
						SpecialId string `json:"specialId"`
						TicketCount string `json:"ticketCount"`
						Deprecated19 bool `json:"deprecated19"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
						DisplayId string `json:"displayId"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						Exp float64 `json:"exp"`
						PushCommentStatus bool `json:"pushCommentStatus"`
						Verified bool `json:"verified"`
						Deprecated6 float64 `json:"deprecated6"`
						UserAttr struct {
							IsMuted bool `json:"isMuted"`
							IsAdmin bool `json:"isAdmin"`
							IsSuperAdmin bool `json:"isSuperAdmin"`
							MuteDuration string `json:"muteDuration"`
						} `json:"userAttr"`
						DisableIchat float64 `json:"disableIchat"`
						PushFriendAction bool `json:"pushFriendAction"`
						IsSubscribe bool `json:"isSubscribe"`
						PayScore string `json:"payScore"`
						Deprecated13 float64 `json:"deprecated13"`
						Deprecated15 float64 `json:"deprecated15"`
						BlockStatus float64 `json:"blockStatus"`
						IdStr string `json:"idStr"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						PushVideoPost bool `json:"pushVideoPost"`
						Deprecated5 string `json:"deprecated5"`
						VerifiedContent string `json:"verifiedContent"`
						SecUid string `json:"secUid"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						Deprecated28 bool `json:"deprecated28"`
						Secret float64 `json:"secret"`
						IsFollowing bool `json:"isFollowing"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						IsBlock bool `json:"isBlock"`
						Deprecated2 float64 `json:"deprecated2"`
						Deprecated7 string `json:"deprecated7"`
						ModifyTime string `json:"modifyTime"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						LinkMicStats float64 `json:"linkMicStats"`
						PayScores string `json:"payScores"`
						PushDigg bool `json:"pushDigg"`
						PayGrade struct {
							GradeBanner string `json:"gradeBanner"`
							Deprecated20 string `json:"deprecated20"`
							NextName string `json:"nextName"`
							Deprecated23 string `json:"deprecated23"`
							UpgradeNeedConsume string `json:"upgradeNeedConsume"`
							Name string `json:"name"`
							Level string `json:"level"`
							Deprecated25 string `json:"deprecated25"`
							GradeDescribe string `json:"gradeDescribe"`
							Deprecated24 string `json:"deprecated24"`
							Deprecated26 string `json:"deprecated26"`
							ScreenChatType string `json:"screenChatType"`
							Score string `json:"score"`
							Deprecated22 string `json:"deprecated22"`
							NextPrivileges string `json:"nextPrivileges"`
						} `json:"payGrade"`
						CommentRestrict float64 `json:"commentRestrict"`
						FollowStatus string `json:"followStatus"`
						PushIchat bool `json:"pushIchat"`
						Deprecated12 float64 `json:"deprecated12"`
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
						FanTicketCount string `json:"fanTicketCount"`
						PushStatus bool `json:"pushStatus"`
						Deprecated17 bool `json:"deprecated17"`
						ScmLabel string `json:"scmLabel"`
					} `json:"user"`
					WithColon bool `json:"withColon"`
				} `json:"userValue"`
			} `json:"piecesList"`
		} `json:"displayText"`
		AnchorFoldType string `json:"anchorFoldType"`
		MsgId string `json:"msgId"`
		Monitor float64 `json:"monitor"`
		PriorityScore string `json:"priorityScore"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
		ClientSendTime string `json:"clientSendTime"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		Method string `json:"method"`
		IsShowMsg bool `json:"isShowMsg"`
		Describe string `json:"describe"`
		FoldType string `json:"foldType"`
		MsgProcessFilterK string `json:"msgProcessFilterK"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
	} `json:"common"`
	User struct {
		AllowShareShowProfile bool `json:"allowShareShowProfile"`
		AllowShowMyAction bool `json:"allowShowMyAction"`
		IchatRestrictType float64 `json:"ichatRestrictType"`
		PushVideoPost bool `json:"pushVideoPost"`
		WithCommercePermission bool `json:"withCommercePermission"`
		UserRole float64 `json:"userRole"`
		Deprecated16 bool `json:"deprecated16"`
		FoldStrangerChat bool `json:"foldStrangerChat"`
		PushFriendAction bool `json:"pushFriendAction"`
		Deprecated17 bool `json:"deprecated17"`
		WithCarManagementPermission bool `json:"withCarManagementPermission"`
		Secret float64 `json:"secret"`
		ScmLabel string `json:"scmLabel"`
		BioDescription string `json:"bioDescription"`
		PayGrade struct {
			Deprecated20 string `json:"deprecated20"`
			NextName string `json:"nextName"`
			UpgradeNeedConsume string `json:"upgradeNeedConsume"`
			Level string `json:"level"`
			Score string `json:"score"`
			GradeBanner string `json:"gradeBanner"`
			Name string `json:"name"`
			Deprecated23 string `json:"deprecated23"`
			Deprecated24 string `json:"deprecated24"`
			Deprecated26 string `json:"deprecated26"`
			ScreenChatType string `json:"screenChatType"`
			Deprecated22 string `json:"deprecated22"`
			Deprecated25 string `json:"deprecated25"`
			GradeDescribe string `json:"gradeDescribe"`
			NextPrivileges string `json:"nextPrivileges"`
		} `json:"payGrade"`
		DisableIchat float64 `json:"disableIchat"`
		IdStr string `json:"idStr"`
		PushDigg bool `json:"pushDigg"`
		ShareQrcodeUri string `json:"shareQrcodeUri"`
		Deprecated21 string `json:"deprecated21"`
		Constellation string `json:"constellation"`
		Deprecated7 string `json:"deprecated7"`
		Deprecated5 string `json:"deprecated5"`
		Deprecated12 float64 `json:"deprecated12"`
		Deprecated19 bool `json:"deprecated19"`
		AllowUseLinkmic bool `json:"allowUseLinkmic"`
		NeedProfileGuide bool `json:"needProfileGuide"`
		PushCommentStatus bool `json:"pushCommentStatus"`
		IsSubscribe bool `json:"isSubscribe"`
		Deprecated4 string `json:"deprecated4"`
		Status float64 `json:"status"`
		FollowInfo struct {
			FollowingCount string `json:"followingCount"`
			FollowerCount string `json:"followerCount"`
			FollowStatus string `json:"followStatus"`
			PushStatus string `json:"pushStatus"`
		} `json:"followInfo"`
		Deprecated15 float64 `json:"deprecated15"`
		AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
		AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
		PushFollow bool `json:"pushFollow"`
		Id string `json:"id"`
		ModifyTime string `json:"modifyTime"`
		Deprecated13 float64 `json:"deprecated13"`
		AllowStrangeComment bool `json:"allowStrangeComment"`
		IsFollower bool `json:"isFollower"`
		PushVideoRecommend bool `json:"pushVideoRecommend"`
		VerifiedReason string `json:"verifiedReason"`
		Deprecated1 string `json:"deprecated1"`
		TopVipNo string `json:"topVipNo"`
		LinkMicStats float64 `json:"linkMicStats"`
		AllowFindByContacts bool `json:"allowFindByContacts"`
		AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
		AllowShowInGossip bool `json:"allowShowInGossip"`
		SpecialId string `json:"specialId"`
		Deprecated6 float64 `json:"deprecated6"`
		TicketCount string `json:"ticketCount"`
		IsBlock bool `json:"isBlock"`
		Deprecated2 float64 `json:"deprecated2"`
		Deprecated8 float64 `json:"deprecated8"`
		PayScore string `json:"payScore"`
		BlockStatus float64 `json:"blockStatus"`
		Exp float64 `json:"exp"`
		PayScores string `json:"payScores"`
		Deprecated3 float64 `json:"deprecated3"`
		SecUid string `json:"secUid"`
		EnableIchatImg string `json:"enableIchatImg"`
		VerifiedContent string `json:"verifiedContent"`
		BgImgUrl string `json:"bgImgUrl"`
		Deprecated18 string `json:"deprecated18"`
		FanTicketCount string `json:"fanTicketCount"`
		Deprecated29 string `json:"deprecated29"`
		PushStatus bool `json:"pushStatus"`
		UserAttr struct {
			MuteDuration string `json:"muteDuration"`
			IsMuted bool `json:"isMuted"`
			IsAdmin bool `json:"isAdmin"`
			IsSuperAdmin bool `json:"isSuperAdmin"`
		} `json:"userAttr"`
		DisplayId string `json:"displayId"`
		Nickname string `json:"nickname"`
		Verified bool `json:"verified"`
		CommentRestrict float64 `json:"commentRestrict"`
		IsFollowing bool `json:"isFollowing"`
		AvatarThumb struct {
			IsAnimated bool `json:"isAnimated"`
			UrlListList []string `json:"urlListList"`
			Uri string `json:"uri"`
			Height string `json:"height"`
			Width string `json:"width"`
			AvgColor string `json:"avgColor"`
			ImageType float64 `json:"imageType"`
			OpenWebUrl string `json:"openWebUrl"`
		} `json:"avatarThumb"`
		WithFusionShopEntry bool `json:"withFusionShopEntry"`
		FollowStatus string `json:"followStatus"`
		Deprecated28 bool `json:"deprecated28"`
		PushIchat bool `json:"pushIchat"`
		CreateTime string `json:"createTime"`
	} `json:"user"`
	ShareType string `json:"shareType"`
}
