package msgs
type WebcastLikeMessage struct {
	Color string `json:"color"`
	Icon string `json:"icon"`
	EffectCnt string `json:"effectCnt"`
	LikeEffectList []*struct {
		Version string `json:"version"`
		EffectCnt string `json:"effectCnt"`
		EffectIntervalMs string `json:"effectIntervalMs"`
	} `json:"likeEffectList"`
	PublicAreaMessageCommon struct {
		AnchorReleaseToScrollArea bool `json:"anchorReleaseToScrollArea"`
		ScrollGapCount string `json:"scrollGapCount"`
		AnchorScrollGapCount string `json:"anchorScrollGapCount"`
		ReleaseToScrollArea bool `json:"releaseToScrollArea"`
	} `json:"publicAreaMessageCommon"`
	Streamer string `json:"streamer"`
	Common struct {
		Describe string `json:"describe"`
		DisplayText struct {
			DefaultFormat struct {
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
				UseHeighLightColor bool `json:"useHeighLightColor"`
				UseRemoteClor bool `json:"useRemoteClor"`
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
			} `json:"defaultFormat"`
			PiecesList []*struct {
				Type float64 `json:"type"`
				StringValue string `json:"stringValue"`
				UserValue struct {
					WithColon bool `json:"withColon"`
					User struct {
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
						BlockStatus float64 `json:"blockStatus"`
						FanTicketCount string `json:"fanTicketCount"`
						Deprecated1 string `json:"deprecated1"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						PayScores string `json:"payScores"`
						PushStatus bool `json:"pushStatus"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						Deprecated12 float64 `json:"deprecated12"`
						IsFollowing bool `json:"isFollowing"`
						DisableIchat float64 `json:"disableIchat"`
						IdStr string `json:"idStr"`
						PushDigg bool `json:"pushDigg"`
						IsSubscribe bool `json:"isSubscribe"`
						Id string `json:"id"`
						Deprecated2 float64 `json:"deprecated2"`
						Verified bool `json:"verified"`
						CommentRestrict float64 `json:"commentRestrict"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						ScmLabel string `json:"scmLabel"`
						Deprecated13 float64 `json:"deprecated13"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						PushFollow bool `json:"pushFollow"`
						Deprecated7 string `json:"deprecated7"`
						ModifyTime string `json:"modifyTime"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
						FollowStatus string `json:"followStatus"`
						Deprecated3 float64 `json:"deprecated3"`
						Deprecated4 string `json:"deprecated4"`
						SecUid string `json:"secUid"`
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						Deprecated18 string `json:"deprecated18"`
						Status float64 `json:"status"`
						TopVipNo string `json:"topVipNo"`
						WithCommercePermission bool `json:"withCommercePermission"`
						EnableIchatImg string `json:"enableIchatImg"`
						PushIchat bool `json:"pushIchat"`
						Deprecated17 bool `json:"deprecated17"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						Deprecated21 string `json:"deprecated21"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						Exp float64 `json:"exp"`
						BioDescription string `json:"bioDescription"`
						Deprecated5 string `json:"deprecated5"`
						Secret float64 `json:"secret"`
						VerifiedContent string `json:"verifiedContent"`
						Deprecated8 float64 `json:"deprecated8"`
						SpecialId string `json:"specialId"`
						Deprecated19 bool `json:"deprecated19"`
						Deprecated29 string `json:"deprecated29"`
						PushVideoPost bool `json:"pushVideoPost"`
						VerifiedReason string `json:"verifiedReason"`
						Nickname string `json:"nickname"`
						Deprecated6 float64 `json:"deprecated6"`
						PayScore string `json:"payScore"`
						Deprecated16 bool `json:"deprecated16"`
						PushCommentStatus bool `json:"pushCommentStatus"`
						PushFriendAction bool `json:"pushFriendAction"`
						IsBlock bool `json:"isBlock"`
						TicketCount string `json:"ticketCount"`
						LinkMicStats float64 `json:"linkMicStats"`
						DisplayId string `json:"displayId"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						BgImgUrl string `json:"bgImgUrl"`
						Constellation string `json:"constellation"`
						Deprecated28 bool `json:"deprecated28"`
						CreateTime string `json:"createTime"`
						UserRole float64 `json:"userRole"`
						Deprecated15 float64 `json:"deprecated15"`
						IsFollower bool `json:"isFollower"`
					} `json:"user"`
				} `json:"userValue"`
			} `json:"piecesList"`
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
		} `json:"displayText"`
		MsgProcessFilterK string `json:"msgProcessFilterK"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		Method string `json:"method"`
		RoomId string `json:"roomId"`
		CreateTime string `json:"createTime"`
		LogId string `json:"logId"`
		ToIdc string `json:"toIdc"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		ClientSendTime string `json:"clientSendTime"`
		MsgId string `json:"msgId"`
		FoldType string `json:"foldType"`
		AnchorFoldType string `json:"anchorFoldType"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
		IsShowMsg bool `json:"isShowMsg"`
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
		Monitor float64 `json:"monitor"`
		PriorityScore string `json:"priorityScore"`
		FromIdc string `json:"fromIdc"`
	} `json:"common"`
	Total string `json:"total"`
	User struct {
		DisableIchat float64 `json:"disableIchat"`
		Exp float64 `json:"exp"`
		PayScores string `json:"payScores"`
		Deprecated5 string `json:"deprecated5"`
		UserAttr struct {
			IsMuted bool `json:"isMuted"`
			IsAdmin bool `json:"isAdmin"`
			IsSuperAdmin bool `json:"isSuperAdmin"`
			MuteDuration string `json:"muteDuration"`
		} `json:"userAttr"`
		AllowShowMyAction bool `json:"allowShowMyAction"`
		Deprecated18 string `json:"deprecated18"`
		AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
		IsFollower bool `json:"isFollower"`
		NeedProfileGuide bool `json:"needProfileGuide"`
		PushCommentStatus bool `json:"pushCommentStatus"`
		AvatarThumb struct {
			Height string `json:"height"`
			Width string `json:"width"`
			AvgColor string `json:"avgColor"`
			ImageType float64 `json:"imageType"`
			OpenWebUrl string `json:"openWebUrl"`
			IsAnimated bool `json:"isAnimated"`
			UrlListList []string `json:"urlListList"`
			Uri string `json:"uri"`
		} `json:"avatarThumb"`
		SpecialId string `json:"specialId"`
		Deprecated12 float64 `json:"deprecated12"`
		PushFriendAction bool `json:"pushFriendAction"`
		ScmLabel string `json:"scmLabel"`
		IsSubscribe bool `json:"isSubscribe"`
		WithFusionShopEntry bool `json:"withFusionShopEntry"`
		SecUid string `json:"secUid"`
		AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
		CommentRestrict float64 `json:"commentRestrict"`
		Id string `json:"id"`
		Status float64 `json:"status"`
		TopVipNo string `json:"topVipNo"`
		PushVideoRecommend bool `json:"pushVideoRecommend"`
		PushFollow bool `json:"pushFollow"`
		Deprecated1 string `json:"deprecated1"`
		Deprecated6 float64 `json:"deprecated6"`
		Secret float64 `json:"secret"`
		TicketCount string `json:"ticketCount"`
		PushVideoPost bool `json:"pushVideoPost"`
		Deprecated21 string `json:"deprecated21"`
		AllowUseLinkmic bool `json:"allowUseLinkmic"`
		Deprecated16 bool `json:"deprecated16"`
		FollowStatus string `json:"followStatus"`
		ModifyTime string `json:"modifyTime"`
		FoldStrangerChat bool `json:"foldStrangerChat"`
		PushIchat bool `json:"pushIchat"`
		Deprecated29 string `json:"deprecated29"`
		IchatRestrictType float64 `json:"ichatRestrictType"`
		IdStr string `json:"idStr"`
		Deprecated17 bool `json:"deprecated17"`
		DisplayId string `json:"displayId"`
		Deprecated13 float64 `json:"deprecated13"`
		BgImgUrl string `json:"bgImgUrl"`
		EnableIchatImg string `json:"enableIchatImg"`
		Nickname string `json:"nickname"`
		Deprecated19 bool `json:"deprecated19"`
		CreateTime string `json:"createTime"`
		PayGrade struct {
			NextPrivileges string `json:"nextPrivileges"`
			Name string `json:"name"`
			Deprecated23 string `json:"deprecated23"`
			Deprecated24 string `json:"deprecated24"`
			NextName string `json:"nextName"`
			Deprecated22 string `json:"deprecated22"`
			GradeBanner string `json:"gradeBanner"`
			Deprecated20 string `json:"deprecated20"`
			ScreenChatType string `json:"screenChatType"`
			UpgradeNeedConsume string `json:"upgradeNeedConsume"`
			GradeDescribe string `json:"gradeDescribe"`
			Score string `json:"score"`
			Level string `json:"level"`
			Deprecated25 string `json:"deprecated25"`
			Deprecated26 string `json:"deprecated26"`
		} `json:"payGrade"`
		AllowFindByContacts bool `json:"allowFindByContacts"`
		PushStatus bool `json:"pushStatus"`
		BlockStatus float64 `json:"blockStatus"`
		PushDigg bool `json:"pushDigg"`
		IsBlock bool `json:"isBlock"`
		Deprecated3 float64 `json:"deprecated3"`
		PayScore string `json:"payScore"`
		WithCommercePermission bool `json:"withCommercePermission"`
		AllowShareShowProfile bool `json:"allowShareShowProfile"`
		AllowStrangeComment bool `json:"allowStrangeComment"`
		Deprecated7 string `json:"deprecated7"`
		FollowInfo struct {
			PushStatus string `json:"pushStatus"`
			FollowingCount string `json:"followingCount"`
			FollowerCount string `json:"followerCount"`
			FollowStatus string `json:"followStatus"`
		} `json:"followInfo"`
		LinkMicStats float64 `json:"linkMicStats"`
		Deprecated15 float64 `json:"deprecated15"`
		Deprecated4 string `json:"deprecated4"`
		FanTicketCount string `json:"fanTicketCount"`
		Deprecated28 bool `json:"deprecated28"`
		IsFollowing bool `json:"isFollowing"`
		VerifiedReason string `json:"verifiedReason"`
		Deprecated2 float64 `json:"deprecated2"`
		BioDescription string `json:"bioDescription"`
		ShareQrcodeUri string `json:"shareQrcodeUri"`
		UserRole float64 `json:"userRole"`
		Constellation string `json:"constellation"`
		WithCarManagementPermission bool `json:"withCarManagementPermission"`
		Deprecated8 float64 `json:"deprecated8"`
		AllowShowInGossip bool `json:"allowShowInGossip"`
		AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
		Verified bool `json:"verified"`
		VerifiedContent string `json:"verifiedContent"`
	} `json:"user"`
	SpecifiedDisplayTextList []*struct {
		Uid string `json:"uid"`
		DisplayText struct {
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
			DefaultFormat struct {
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
				UseHeighLightColor bool `json:"useHeighLightColor"`
				UseRemoteClor bool `json:"useRemoteClor"`
			} `json:"defaultFormat"`
			PiecesList []*struct {
				Type float64 `json:"type"`
				StringValue string `json:"stringValue"`
				UserValue struct {
					User struct {
						PushCommentStatus bool `json:"pushCommentStatus"`
						SpecialId string `json:"specialId"`
						Deprecated13 float64 `json:"deprecated13"`
						Constellation string `json:"constellation"`
						EnableIchatImg string `json:"enableIchatImg"`
						PushVideoPost bool `json:"pushVideoPost"`
						Id string `json:"id"`
						Deprecated4 string `json:"deprecated4"`
						CreateTime string `json:"createTime"`
						Deprecated21 string `json:"deprecated21"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						Deprecated19 bool `json:"deprecated19"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						Verified bool `json:"verified"`
						Deprecated6 float64 `json:"deprecated6"`
						Secret float64 `json:"secret"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						VerifiedReason string `json:"verifiedReason"`
						Deprecated1 string `json:"deprecated1"`
						Deprecated29 string `json:"deprecated29"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						PushIchat bool `json:"pushIchat"`
						CommentRestrict float64 `json:"commentRestrict"`
						Deprecated5 string `json:"deprecated5"`
						SecUid string `json:"secUid"`
						BlockStatus float64 `json:"blockStatus"`
						Deprecated8 float64 `json:"deprecated8"`
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
						IsFollower bool `json:"isFollower"`
						PushDigg bool `json:"pushDigg"`
						Deprecated17 bool `json:"deprecated17"`
						Deprecated2 float64 `json:"deprecated2"`
						Deprecated15 float64 `json:"deprecated15"`
						FollowStatus string `json:"followStatus"`
						Deprecated7 string `json:"deprecated7"`
						Exp float64 `json:"exp"`
						FanTicketCount string `json:"fanTicketCount"`
						IsBlock bool `json:"isBlock"`
						Deprecated28 bool `json:"deprecated28"`
						IsFollowing bool `json:"isFollowing"`
						IsSubscribe bool `json:"isSubscribe"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						ScmLabel string `json:"scmLabel"`
						Nickname string `json:"nickname"`
						Deprecated3 float64 `json:"deprecated3"`
						UserRole float64 `json:"userRole"`
						Deprecated18 string `json:"deprecated18"`
						PushFollow bool `json:"pushFollow"`
						BioDescription string `json:"bioDescription"`
						TopVipNo string `json:"topVipNo"`
						PayScore string `json:"payScore"`
						Deprecated12 float64 `json:"deprecated12"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						BgImgUrl string `json:"bgImgUrl"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						IdStr string `json:"idStr"`
						Status float64 `json:"status"`
						LinkMicStats float64 `json:"linkMicStats"`
						DisplayId string `json:"displayId"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						PayScores string `json:"payScores"`
						PushFriendAction bool `json:"pushFriendAction"`
						WithCommercePermission bool `json:"withCommercePermission"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						DisableIchat float64 `json:"disableIchat"`
						PushStatus bool `json:"pushStatus"`
						Deprecated16 bool `json:"deprecated16"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						ModifyTime string `json:"modifyTime"`
						TicketCount string `json:"ticketCount"`
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						VerifiedContent string `json:"verifiedContent"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
					} `json:"user"`
					WithColon bool `json:"withColon"`
				} `json:"userValue"`
			} `json:"piecesList"`
		} `json:"displayText"`
	} `json:"specifiedDisplayTextList"`
	Count string `json:"count"`
}
