package msgs
type WebcastRoomUserSeqMessage struct {
	Common struct {
		MsgProcessFilterK string `json:"msgProcessFilterK"`
		FoldType string `json:"foldType"`
		CreateTime string `json:"createTime"`
		Describe string `json:"describe"`
		AnchorFoldType string `json:"anchorFoldType"`
		PriorityScore string `json:"priorityScore"`
		LogId string `json:"logId"`
		ToIdc string `json:"toIdc"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
		MsgId string `json:"msgId"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
		ClientSendTime string `json:"clientSendTime"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		IsShowMsg bool `json:"isShowMsg"`
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		Method string `json:"method"`
		Monitor float64 `json:"monitor"`
		FromIdc string `json:"fromIdc"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
		RoomId string `json:"roomId"`
	} `json:"common"`
	RanksList []*struct {
		Score string `json:"score"`
		User struct {
			Verified bool `json:"verified"`
			Deprecated6 float64 `json:"deprecated6"`
			IsFollowing bool `json:"isFollowing"`
			Id string `json:"id"`
			Exp float64 `json:"exp"`
			PayScores string `json:"payScores"`
			PushVideoRecommend bool `json:"pushVideoRecommend"`
			Deprecated15 float64 `json:"deprecated15"`
			AllowShowInGossip bool `json:"allowShowInGossip"`
			PushFollow bool `json:"pushFollow"`
			PushIchat bool `json:"pushIchat"`
			WithCommercePermission bool `json:"withCommercePermission"`
			Secret float64 `json:"secret"`
			AllowStrangeComment bool `json:"allowStrangeComment"`
			Deprecated28 bool `json:"deprecated28"`
			NeedProfileGuide bool `json:"needProfileGuide"`
			ScmLabel string `json:"scmLabel"`
			Nickname string `json:"nickname"`
			Deprecated19 bool `json:"deprecated19"`
			FoldStrangerChat bool `json:"foldStrangerChat"`
			TopVipNo string `json:"topVipNo"`
			Deprecated5 string `json:"deprecated5"`
			LinkMicStats float64 `json:"linkMicStats"`
			AllowShareShowProfile bool `json:"allowShareShowProfile"`
			Deprecated29 string `json:"deprecated29"`
			PushVideoPost bool `json:"pushVideoPost"`
			BioDescription string `json:"bioDescription"`
			Deprecated8 float64 `json:"deprecated8"`
			VerifiedContent string `json:"verifiedContent"`
			IdStr string `json:"idStr"`
			VerifiedReason string `json:"verifiedReason"`
			WithCarManagementPermission bool `json:"withCarManagementPermission"`
			Deprecated3 float64 `json:"deprecated3"`
			SpecialId string `json:"specialId"`
			WithFusionShopEntry bool `json:"withFusionShopEntry"`
			Deprecated16 bool `json:"deprecated16"`
			IsFollower bool `json:"isFollower"`
			PayGrade struct {
				Deprecated22 string `json:"deprecated22"`
				ScreenChatType string `json:"screenChatType"`
				Score string `json:"score"`
				NextName string `json:"nextName"`
				Deprecated24 string `json:"deprecated24"`
				GradeDescribe string `json:"gradeDescribe"`
				Deprecated20 string `json:"deprecated20"`
				Name string `json:"name"`
				UpgradeNeedConsume string `json:"upgradeNeedConsume"`
				Level string `json:"level"`
				Deprecated23 string `json:"deprecated23"`
				Deprecated25 string `json:"deprecated25"`
				Deprecated26 string `json:"deprecated26"`
				NextPrivileges string `json:"nextPrivileges"`
				GradeBanner string `json:"gradeBanner"`
			} `json:"payGrade"`
			AllowFindByContacts bool `json:"allowFindByContacts"`
			CommentRestrict float64 `json:"commentRestrict"`
			PushDigg bool `json:"pushDigg"`
			UserAttr struct {
				IsMuted bool `json:"isMuted"`
				IsAdmin bool `json:"isAdmin"`
				IsSuperAdmin bool `json:"isSuperAdmin"`
				MuteDuration string `json:"muteDuration"`
			} `json:"userAttr"`
			Deprecated21 string `json:"deprecated21"`
			UserRole float64 `json:"userRole"`
			AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
			BgImgUrl string `json:"bgImgUrl"`
			Constellation string `json:"constellation"`
			FanTicketCount string `json:"fanTicketCount"`
			DisplayId string `json:"displayId"`
			PushFriendAction bool `json:"pushFriendAction"`
			IsSubscribe bool `json:"isSubscribe"`
			ModifyTime string `json:"modifyTime"`
			SecUid string `json:"secUid"`
			Deprecated12 float64 `json:"deprecated12"`
			AllowShowMyAction bool `json:"allowShowMyAction"`
			AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
			BlockStatus float64 `json:"blockStatus"`
			EnableIchatImg string `json:"enableIchatImg"`
			Deprecated1 string `json:"deprecated1"`
			IsBlock bool `json:"isBlock"`
			FollowStatus string `json:"followStatus"`
			ShareQrcodeUri string `json:"shareQrcodeUri"`
			PayScore string `json:"payScore"`
			TicketCount string `json:"ticketCount"`
			PushStatus bool `json:"pushStatus"`
			Deprecated2 float64 `json:"deprecated2"`
			Deprecated18 string `json:"deprecated18"`
			IchatRestrictType float64 `json:"ichatRestrictType"`
			AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
			AvatarThumb struct {
				Height string `json:"height"`
				Width string `json:"width"`
				AvgColor string `json:"avgColor"`
				ImageType float64 `json:"imageType"`
				OpenWebUrl string `json:"openWebUrl"`
				IsAnimated bool `json:"isAnimated"`
				UrlListList []string `json:"urlListList"`
				Uri string `json:"uri"`
			} `json:"avatarThumb"`
			CreateTime string `json:"createTime"`
			Deprecated13 float64 `json:"deprecated13"`
			AllowUseLinkmic bool `json:"allowUseLinkmic"`
			Deprecated17 bool `json:"deprecated17"`
			Deprecated4 string `json:"deprecated4"`
			Status float64 `json:"status"`
			DisableIchat float64 `json:"disableIchat"`
			PushCommentStatus bool `json:"pushCommentStatus"`
			Deprecated7 string `json:"deprecated7"`
		} `json:"user"`
		Rank string `json:"rank"`
		Delta string `json:"delta"`
	} `json:"ranksList"`
	PopStr string `json:"popStr"`
	TotalUser string `json:"totalUser"`
	Streamer string `json:"streamer"`
	Total string `json:"total"`
	Popularity string `json:"popularity"`
	Anonymous string `json:"anonymous"`
}
