package msgs
type WebcastMemberMessage struct {
	Common struct {
		RoomId string `json:"roomId"`
		Monitor float64 `json:"monitor"`
		MsgProcessFilterK string `json:"msgProcessFilterK"`
		Method string `json:"method"`
		CreateTime string `json:"createTime"`
		MsgProcessFilterV string `json:"msgProcessFilterV"`
		AnchorFoldTypeForWeb string `json:"anchorFoldTypeForWeb"`
		ClientSendTime string `json:"clientSendTime"`
		MsgId string `json:"msgId"`
		IsShowMsg bool `json:"isShowMsg"`
		DisplayText struct {
			Key string `json:"key"`
			DefaultPattern string `json:"defaultPattern"`
			DefaultFormat struct {
				UseRemoteClor bool `json:"useRemoteClor"`
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
				UseHeighLightColor bool `json:"useHeighLightColor"`
			} `json:"defaultFormat"`
			PiecesList []*struct {
				Type float64 `json:"type"`
				Format struct {
					Italic bool `json:"italic"`
					Weight float64 `json:"weight"`
					ItalicAngle float64 `json:"italicAngle"`
					FontSize float64 `json:"fontSize"`
					UseHeighLightColor bool `json:"useHeighLightColor"`
					UseRemoteClor bool `json:"useRemoteClor"`
					Color string `json:"color"`
					Bold bool `json:"bold"`
				} `json:"format"`
				StringValue string `json:"stringValue"`
				UserValue struct {
					User struct {
						PushFollow bool `json:"pushFollow"`
						ScmLabel string `json:"scmLabel"`
						Deprecated1 string `json:"deprecated1"`
						Secret float64 `json:"secret"`
						UserRole float64 `json:"userRole"`
						AllowFindByContacts bool `json:"allowFindByContacts"`
						AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
						Deprecated29 string `json:"deprecated29"`
						Deprecated6 float64 `json:"deprecated6"`
						PayScore string `json:"payScore"`
						Deprecated13 float64 `json:"deprecated13"`
						Deprecated16 bool `json:"deprecated16"`
						NeedProfileGuide bool `json:"needProfileGuide"`
						Deprecated3 float64 `json:"deprecated3"`
						Deprecated8 float64 `json:"deprecated8"`
						PushCommentStatus bool `json:"pushCommentStatus"`
						PushFriendAction bool `json:"pushFriendAction"`
						VerifiedReason string `json:"verifiedReason"`
						Nickname string `json:"nickname"`
						Deprecated2 float64 `json:"deprecated2"`
						Verified bool `json:"verified"`
						PushVideoRecommend bool `json:"pushVideoRecommend"`
						VerifiedContent string `json:"verifiedContent"`
						FollowStatus string `json:"followStatus"`
						AvatarThumb struct {
							IsAnimated bool `json:"isAnimated"`
							UrlListList []string `json:"urlListList"`
							Uri string `json:"uri"`
							Height string `json:"height"`
							Width string `json:"width"`
							AvgColor string `json:"avgColor"`
							ImageType float64 `json:"imageType"`
							OpenWebUrl string `json:"openWebUrl"`
						} `json:"avatarThumb"`
						UserAttr struct {
							IsMuted bool `json:"isMuted"`
							IsAdmin bool `json:"isAdmin"`
							IsSuperAdmin bool `json:"isSuperAdmin"`
							MuteDuration string `json:"muteDuration"`
						} `json:"userAttr"`
						Deprecated21 string `json:"deprecated21"`
						AllowShowInGossip bool `json:"allowShowInGossip"`
						IsFollowing bool `json:"isFollowing"`
						DisableIchat float64 `json:"disableIchat"`
						Deprecated12 float64 `json:"deprecated12"`
						EnableIchatImg string `json:"enableIchatImg"`
						IchatRestrictType float64 `json:"ichatRestrictType"`
						Deprecated18 string `json:"deprecated18"`
						PayScores string `json:"payScores"`
						ModifyTime string `json:"modifyTime"`
						WithFusionShopEntry bool `json:"withFusionShopEntry"`
						BgImgUrl string `json:"bgImgUrl"`
						Exp float64 `json:"exp"`
						IdStr string `json:"idStr"`
						PushStatus bool `json:"pushStatus"`
						IsBlock bool `json:"isBlock"`
						BioDescription string `json:"bioDescription"`
						Deprecated4 string `json:"deprecated4"`
						FollowInfo struct {
							FollowStatus string `json:"followStatus"`
							PushStatus string `json:"pushStatus"`
							FollowingCount string `json:"followingCount"`
							FollowerCount string `json:"followerCount"`
						} `json:"followInfo"`
						WithCommercePermission bool `json:"withCommercePermission"`
						AllowStrangeComment bool `json:"allowStrangeComment"`
						CommentRestrict float64 `json:"commentRestrict"`
						BlockStatus float64 `json:"blockStatus"`
						Constellation string `json:"constellation"`
						Status float64 `json:"status"`
						PayGrade struct {
							Deprecated24 string `json:"deprecated24"`
							UpgradeNeedConsume string `json:"upgradeNeedConsume"`
							Score string `json:"score"`
							GradeBanner string `json:"gradeBanner"`
							NextName string `json:"nextName"`
							Deprecated23 string `json:"deprecated23"`
							Deprecated25 string `json:"deprecated25"`
							Deprecated26 string `json:"deprecated26"`
							Level string `json:"level"`
							Deprecated22 string `json:"deprecated22"`
							GradeDescribe string `json:"gradeDescribe"`
							NextPrivileges string `json:"nextPrivileges"`
							Deprecated20 string `json:"deprecated20"`
							Name string `json:"name"`
							ScreenChatType string `json:"screenChatType"`
						} `json:"payGrade"`
						TopVipNo string `json:"topVipNo"`
						LinkMicStats float64 `json:"linkMicStats"`
						SecUid string `json:"secUid"`
						Deprecated15 float64 `json:"deprecated15"`
						Id string `json:"id"`
						Deprecated5 string `json:"deprecated5"`
						Deprecated7 string `json:"deprecated7"`
						ShareQrcodeUri string `json:"shareQrcodeUri"`
						SpecialId string `json:"specialId"`
						DisplayId string `json:"displayId"`
						AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
						IsFollower bool `json:"isFollower"`
						PushIchat bool `json:"pushIchat"`
						IsSubscribe bool `json:"isSubscribe"`
						TicketCount string `json:"ticketCount"`
						FoldStrangerChat bool `json:"foldStrangerChat"`
						Deprecated28 bool `json:"deprecated28"`
						PushDigg bool `json:"pushDigg"`
						PushVideoPost bool `json:"pushVideoPost"`
						CreateTime string `json:"createTime"`
						Deprecated19 bool `json:"deprecated19"`
						AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
						AllowShareShowProfile bool `json:"allowShareShowProfile"`
						FanTicketCount string `json:"fanTicketCount"`
						WithCarManagementPermission bool `json:"withCarManagementPermission"`
						AllowShowMyAction bool `json:"allowShowMyAction"`
						AllowUseLinkmic bool `json:"allowUseLinkmic"`
						Deprecated17 bool `json:"deprecated17"`
					} `json:"user"`
					WithColon bool `json:"withColon"`
				} `json:"userValue"`
			} `json:"piecesList"`
		} `json:"displayText"`
		FoldType string `json:"foldType"`
		AnchorFoldType string `json:"anchorFoldType"`
		PriorityScore string `json:"priorityScore"`
		LogId string `json:"logId"`
		FromIdc string `json:"fromIdc"`
		ToIdc string `json:"toIdc"`
		AnchorPriorityScore string `json:"anchorPriorityScore"`
		RoomMessageHeatLevel string `json:"roomMessageHeatLevel"`
		FoldTypeForWeb string `json:"foldTypeForWeb"`
		DispatchStrategy float64 `json:"dispatchStrategy"`
		Describe string `json:"describe"`
	} `json:"common"`
	ClientEnterSource string `json:"clientEnterSource"`
	ClientLiveReason string `json:"clientLiveReason"`
	ActionDescription string `json:"actionDescription"`
	UserId string `json:"userId"`
	PopStr string `json:"popStr"`
	AnchorDisplayText struct {
		Key string `json:"key"`
		DefaultPattern string `json:"defaultPattern"`
		DefaultFormat struct {
			UseHeighLightColor bool `json:"useHeighLightColor"`
			UseRemoteClor bool `json:"useRemoteClor"`
			Color string `json:"color"`
			Bold bool `json:"bold"`
			Italic bool `json:"italic"`
			Weight float64 `json:"weight"`
			ItalicAngle float64 `json:"italicAngle"`
			FontSize float64 `json:"fontSize"`
		} `json:"defaultFormat"`
		PiecesList []*struct {
			Type float64 `json:"type"`
			Format struct {
				Color string `json:"color"`
				Bold bool `json:"bold"`
				Italic bool `json:"italic"`
				Weight float64 `json:"weight"`
				ItalicAngle float64 `json:"italicAngle"`
				FontSize float64 `json:"fontSize"`
				UseHeighLightColor bool `json:"useHeighLightColor"`
				UseRemoteClor bool `json:"useRemoteClor"`
			} `json:"format"`
			StringValue string `json:"stringValue"`
			UserValue struct {
				User struct {
					IsSubscribe bool `json:"isSubscribe"`
					LinkMicStats float64 `json:"linkMicStats"`
					DisplayId string `json:"displayId"`
					Deprecated18 string `json:"deprecated18"`
					Constellation string `json:"constellation"`
					AllowShowMyAction bool `json:"allowShowMyAction"`
					AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
					AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
					AllowShowInGossip bool `json:"allowShowInGossip"`
					EnableIchatImg string `json:"enableIchatImg"`
					NeedProfileGuide bool `json:"needProfileGuide"`
					CreateTime string `json:"createTime"`
					ShareQrcodeUri string `json:"shareQrcodeUri"`
					PayGrade struct {
						Deprecated20 string `json:"deprecated20"`
						Level string `json:"level"`
						NextPrivileges string `json:"nextPrivileges"`
						NextName string `json:"nextName"`
						Deprecated24 string `json:"deprecated24"`
						ScreenChatType string `json:"screenChatType"`
						UpgradeNeedConsume string `json:"upgradeNeedConsume"`
						Deprecated22 string `json:"deprecated22"`
						Deprecated23 string `json:"deprecated23"`
						GradeDescribe string `json:"gradeDescribe"`
						Name string `json:"name"`
						Deprecated25 string `json:"deprecated25"`
						Deprecated26 string `json:"deprecated26"`
						Score string `json:"score"`
						GradeBanner string `json:"gradeBanner"`
					} `json:"payGrade"`
					PayScores string `json:"payScores"`
					Deprecated15 float64 `json:"deprecated15"`
					Deprecated28 bool `json:"deprecated28"`
					Deprecated16 bool `json:"deprecated16"`
					FollowStatus string `json:"followStatus"`
					PushFollow bool `json:"pushFollow"`
					WithCarManagementPermission bool `json:"withCarManagementPermission"`
					Deprecated2 float64 `json:"deprecated2"`
					Status float64 `json:"status"`
					ModifyTime string `json:"modifyTime"`
					UserAttr struct {
						IsMuted bool `json:"isMuted"`
						IsAdmin bool `json:"isAdmin"`
						IsSuperAdmin bool `json:"isSuperAdmin"`
						MuteDuration string `json:"muteDuration"`
					} `json:"userAttr"`
					DisableIchat float64 `json:"disableIchat"`
					PushDigg bool `json:"pushDigg"`
					VerifiedReason string `json:"verifiedReason"`
					FollowInfo struct {
						FollowingCount string `json:"followingCount"`
						FollowerCount string `json:"followerCount"`
						FollowStatus string `json:"followStatus"`
						PushStatus string `json:"pushStatus"`
					} `json:"followInfo"`
					Deprecated13 float64 `json:"deprecated13"`
					AllowUseLinkmic bool `json:"allowUseLinkmic"`
					Deprecated8 float64 `json:"deprecated8"`
					SecUid string `json:"secUid"`
					PushVideoPost bool `json:"pushVideoPost"`
					IsFollower bool `json:"isFollower"`
					IsBlock bool `json:"isBlock"`
					Deprecated3 float64 `json:"deprecated3"`
					Secret float64 `json:"secret"`
					WithFusionShopEntry bool `json:"withFusionShopEntry"`
					BgImgUrl string `json:"bgImgUrl"`
					Deprecated29 string `json:"deprecated29"`
					VerifiedContent string `json:"verifiedContent"`
					AllowShareShowProfile bool `json:"allowShareShowProfile"`
					Exp float64 `json:"exp"`
					PushFriendAction bool `json:"pushFriendAction"`
					ScmLabel string `json:"scmLabel"`
					PayScore string `json:"payScore"`
					BlockStatus float64 `json:"blockStatus"`
					FanTicketCount string `json:"fanTicketCount"`
					PushCommentStatus bool `json:"pushCommentStatus"`
					BioDescription string `json:"bioDescription"`
					Verified bool `json:"verified"`
					TicketCount string `json:"ticketCount"`
					Deprecated17 bool `json:"deprecated17"`
					WithCommercePermission bool `json:"withCommercePermission"`
					AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
					IsFollowing bool `json:"isFollowing"`
					Deprecated1 string `json:"deprecated1"`
					Deprecated5 string `json:"deprecated5"`
					Deprecated6 float64 `json:"deprecated6"`
					Deprecated7 string `json:"deprecated7"`
					Deprecated19 bool `json:"deprecated19"`
					Id string `json:"id"`
					TopVipNo string `json:"topVipNo"`
					Deprecated21 string `json:"deprecated21"`
					UserRole float64 `json:"userRole"`
					AllowFindByContacts bool `json:"allowFindByContacts"`
					AllowStrangeComment bool `json:"allowStrangeComment"`
					CommentRestrict float64 `json:"commentRestrict"`
					AvatarThumb struct {
						IsAnimated bool `json:"isAnimated"`
						UrlListList []string `json:"urlListList"`
						Uri string `json:"uri"`
						Height string `json:"height"`
						Width string `json:"width"`
						AvgColor string `json:"avgColor"`
						ImageType float64 `json:"imageType"`
						OpenWebUrl string `json:"openWebUrl"`
					} `json:"avatarThumb"`
					SpecialId string `json:"specialId"`
					PushVideoRecommend bool `json:"pushVideoRecommend"`
					FoldStrangerChat bool `json:"foldStrangerChat"`
					IchatRestrictType float64 `json:"ichatRestrictType"`
					IdStr string `json:"idStr"`
					PushStatus bool `json:"pushStatus"`
					Nickname string `json:"nickname"`
					Deprecated4 string `json:"deprecated4"`
					Deprecated12 float64 `json:"deprecated12"`
					PushIchat bool `json:"pushIchat"`
				} `json:"user"`
				WithColon bool `json:"withColon"`
			} `json:"userValue"`
		} `json:"piecesList"`
	} `json:"anchorDisplayText"`
	RankScore string `json:"rankScore"`
	Action string `json:"action"`
	ClientEnterType string `json:"clientEnterType"`
	ActionDuration string `json:"actionDuration"`
	PublicAreaMessageCommon struct {
		AnchorScrollGapCount string `json:"anchorScrollGapCount"`
		ReleaseToScrollArea bool `json:"releaseToScrollArea"`
		AnchorReleaseToScrollArea bool `json:"anchorReleaseToScrollArea"`
		ScrollGapCount string `json:"scrollGapCount"`
	} `json:"publicAreaMessageCommon"`
	MemberCount string `json:"memberCount"`
	TopUserNo string `json:"topUserNo"`
	User struct {
		Deprecated7 string `json:"deprecated7"`
		Secret float64 `json:"secret"`
		IchatRestrictType float64 `json:"ichatRestrictType"`
		VerifiedReason string `json:"verifiedReason"`
		Deprecated3 float64 `json:"deprecated3"`
		Deprecated19 bool `json:"deprecated19"`
		AllowUseLinkmic bool `json:"allowUseLinkmic"`
		AllowOthersDownloadWhenSharingVideo bool `json:"allowOthersDownloadWhenSharingVideo"`
		PushDigg bool `json:"pushDigg"`
		IsBlock bool `json:"isBlock"`
		PayGrade struct {
			Deprecated22 string `json:"deprecated22"`
			NextPrivileges string `json:"nextPrivileges"`
			Deprecated20 string `json:"deprecated20"`
			NextName string `json:"nextName"`
			Level string `json:"level"`
			UpgradeNeedConsume string `json:"upgradeNeedConsume"`
			Deprecated25 string `json:"deprecated25"`
			GradeDescribe string `json:"gradeDescribe"`
			Score string `json:"score"`
			Deprecated23 string `json:"deprecated23"`
			Deprecated26 string `json:"deprecated26"`
			ScreenChatType string `json:"screenChatType"`
			Name string `json:"name"`
			Deprecated24 string `json:"deprecated24"`
			GradeBanner string `json:"gradeBanner"`
		} `json:"payGrade"`
		UserRole float64 `json:"userRole"`
		Deprecated18 string `json:"deprecated18"`
		PayScores string `json:"payScores"`
		PayScore string `json:"payScore"`
		WithFusionShopEntry bool `json:"withFusionShopEntry"`
		AllowOthersDownloadVideo bool `json:"allowOthersDownloadVideo"`
		AllowShareShowProfile bool `json:"allowShareShowProfile"`
		AllowShowMyAction bool `json:"allowShowMyAction"`
		IdStr string `json:"idStr"`
		Nickname string `json:"nickname"`
		Deprecated6 float64 `json:"deprecated6"`
		Deprecated12 float64 `json:"deprecated12"`
		Deprecated29 string `json:"deprecated29"`
		PushFollow bool `json:"pushFollow"`
		Status float64 `json:"status"`
		UserAttr struct {
			IsMuted bool `json:"isMuted"`
			IsAdmin bool `json:"isAdmin"`
			IsSuperAdmin bool `json:"isSuperAdmin"`
			MuteDuration string `json:"muteDuration"`
		} `json:"userAttr"`
		DisableIchat float64 `json:"disableIchat"`
		PushCommentStatus bool `json:"pushCommentStatus"`
		PushVideoPost bool `json:"pushVideoPost"`
		PushVideoRecommend bool `json:"pushVideoRecommend"`
		Verified bool `json:"verified"`
		Deprecated13 float64 `json:"deprecated13"`
		BgImgUrl string `json:"bgImgUrl"`
		Exp float64 `json:"exp"`
		FanTicketCount string `json:"fanTicketCount"`
		ScmLabel string `json:"scmLabel"`
		FollowStatus string `json:"followStatus"`
		IsFollowing bool `json:"isFollowing"`
		Deprecated5 string `json:"deprecated5"`
		TopVipNo string `json:"topVipNo"`
		DisplayId string `json:"displayId"`
		BlockStatus float64 `json:"blockStatus"`
		FoldStrangerChat bool `json:"foldStrangerChat"`
		IsSubscribe bool `json:"isSubscribe"`
		BioDescription string `json:"bioDescription"`
		ModifyTime string `json:"modifyTime"`
		CommentRestrict float64 `json:"commentRestrict"`
		PushFriendAction bool `json:"pushFriendAction"`
		Deprecated17 bool `json:"deprecated17"`
		ShareQrcodeUri string `json:"shareQrcodeUri"`
		TicketCount string `json:"ticketCount"`
		EnableIchatImg string `json:"enableIchatImg"`
		WithCarManagementPermission bool `json:"withCarManagementPermission"`
		PushStatus bool `json:"pushStatus"`
		Deprecated1 string `json:"deprecated1"`
		AvatarThumb struct {
			IsAnimated bool `json:"isAnimated"`
			UrlListList []string `json:"urlListList"`
			Uri string `json:"uri"`
			Height string `json:"height"`
			Width string `json:"width"`
			AvgColor string `json:"avgColor"`
			ImageType float64 `json:"imageType"`
			OpenWebUrl string `json:"openWebUrl"`
		} `json:"avatarThumb"`
		AllowFindByContacts bool `json:"allowFindByContacts"`
		AllowStrangeComment bool `json:"allowStrangeComment"`
		Deprecated28 bool `json:"deprecated28"`
		IsFollower bool `json:"isFollower"`
		Deprecated2 float64 `json:"deprecated2"`
		FollowInfo struct {
			FollowingCount string `json:"followingCount"`
			FollowerCount string `json:"followerCount"`
			FollowStatus string `json:"followStatus"`
			PushStatus string `json:"pushStatus"`
		} `json:"followInfo"`
		Deprecated16 bool `json:"deprecated16"`
		NeedProfileGuide bool `json:"needProfileGuide"`
		Id string `json:"id"`
		CreateTime string `json:"createTime"`
		WithCommercePermission bool `json:"withCommercePermission"`
		Deprecated8 float64 `json:"deprecated8"`
		SecUid string `json:"secUid"`
		AllowShowInGossip bool `json:"allowShowInGossip"`
		AllowUnfollowerComment bool `json:"allowUnfollowerComment"`
		Constellation string `json:"constellation"`
		Deprecated4 string `json:"deprecated4"`
		SpecialId string `json:"specialId"`
		LinkMicStats float64 `json:"linkMicStats"`
		Deprecated21 string `json:"deprecated21"`
		VerifiedContent string `json:"verifiedContent"`
		Deprecated15 float64 `json:"deprecated15"`
		PushIchat bool `json:"pushIchat"`
	} `json:"user"`
	DisplayStyle float64 `json:"displayStyle"`
	IsSetToAdmin bool `json:"isSetToAdmin"`
	IsTopUser bool `json:"isTopUser"`
	EnterType string `json:"enterType"`
	Streamer string `json:"streamer"`
	UserShareType string `json:"userShareType"`
	KickSource float64 `json:"kickSource"`
	LastSubscriptionAction string `json:"lastSubscriptionAction"`
	AllowPreviewTime string `json:"allowPreviewTime"`
}
